### ISSUE TITLE
GCC failure on pip3 install of 3.17.1

### ISSUE THREAD

**Issue by steerben** [aws/aws-elastic-beanstalk-cli#11]
### Description

Hey,
currently we are not able to install 3.17.1 via pip3.
This versions seems to need gcc as a dependency, which 3.17.0 did not need.
However, even after making sure that gcc is available on the system an error during pip install is thrown.

#### Alpine
```bash
docker run -it alpine sh

apk update
apk add build-base
apk add python3
pip3 install awsebcli
```
#### Ubuntu
```bash
docker run -it ubuntu bash

apt-get update
apt-get install build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
apt-get install python3-pip
pip3 install awsebcli
```

#### Alpine
```
/ # pip3 install awsebcli
Collecting awsebcli
  Using cached awsebcli-3.17.1.tar.gz (242 kB)
Collecting botocore<1.15,>=1.14.0
  Using cached botocore-1.14.11-py2.py3-none-any.whl (5.9 MB)
Collecting cement==2.8.2
  Using cached cement-2.8.2.tar.gz (165 kB)
Collecting colorama<0.4.0,>=0.3.9
  Using cached colorama-0.3.9-py2.py3-none-any.whl (20 kB)
Collecting future<0.17.0,>=0.16.0
  Using cached future-0.16.0.tar.gz (824 kB)
Collecting pathspec==0.5.9
  Using cached pathspec-0.5.9.tar.gz (25 kB)
Collecting python-dateutil<2.8.1,>=2.1
  Using cached python_dateutil-2.8.0-py2.py3-none-any.whl (226 kB)
Collecting PyYAML<5.3,>=5.2
  Using cached PyYAML-5.2.tar.gz (265 kB)
Collecting requests<2.21,>=2.20.1
  Using cached requests-2.20.1-py2.py3-none-any.whl (57 kB)
Requirement already satisfied: setuptools>=20.0 in /usr/lib/python3.8/site-packages (from awsebcli) (41.2.0)
Collecting semantic_version==2.5.0
  Using cached semantic_version-2.5.0-py3-none-any.whl (14 kB)
Collecting six<1.12.0,>=1.11.0
  Using cached six-1.11.0-py2.py3-none-any.whl (10 kB)
Collecting termcolor==1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting urllib3<1.25,>=1.24.1
  Using cached urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
Collecting wcwidth<0.2.0,>=0.1.7
  Using cached wcwidth-0.1.8-py2.py3-none-any.whl (17 kB)
Collecting docker-compose<1.26.0,>=1.25.2
  Using cached docker_compose-1.25.4-py2.py3-none-any.whl (136 kB)
Collecting blessed>=1.9.5
  Using cached blessed-1.17.2-py2.py3-none-any.whl (76 kB)
Collecting docutils<0.16,>=0.10
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.9.4-py2.py3-none-any.whl (24 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting idna<2.8,>=2.5
  Using cached idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting chardet<3.1.0,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting texttable<2,>=0.9.0
  Using cached texttable-1.6.2-py2.py3-none-any.whl (10 kB)
Collecting dockerpty<1,>=0.4.1
  Using cached dockerpty-0.4.1.tar.gz (13 kB)
Collecting jsonschema<4,>=2.5.1
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting docopt<1,>=0.6.1
  Using cached docopt-0.6.2.tar.gz (25 kB)
Collecting websocket-client<1,>=0.32.0
  Using cached websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Collecting docker[ssh]<5,>=3.7.0
  Using cached docker-4.2.0-py2.py3-none-any.whl (143 kB)
Collecting cached-property<2,>=1.2.0
  Using cached cached_property-1.5.1-py2.py3-none-any.whl (6.0 kB)
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting pyrsistent>=0.14.0
  Using cached pyrsistent-0.15.7.tar.gz (107 kB)
Collecting paramiko>=2.4.2; extra == "ssh"
  Using cached paramiko-2.7.1-py2.py3-none-any.whl (206 kB)
Collecting pynacl>=1.0.1
  Downloading PyNaCl-1.3.0.tar.gz (3.4 MB)
     |████████████████████████████████| 3.4 MB 2.6 MB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-bxflbeco/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cffi>=1.4.1; python_implementation != '"'"'PyPy'"'"''
       cwd: None
  Complete output (55 lines):
  Collecting setuptools
    Using cached setuptools-45.1.0-py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Collecting cffi>=1.4.1
    Using cached cffi-1.13.2.tar.gz (460 kB)
  Collecting pycparser
    Using cached pycparser-2.19.tar.gz (158 kB)
  Installing collected packages: setuptools, wheel, pycparser, cffi
      Running setup.py install for pycparser: started
      Running setup.py install for pycparser: finished with status 'done'
      Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l9cqhb7a/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l9cqhb7a/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hfmcydse/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-bxflbeco/overlay --compile --install-headers /tmp/pip-build-env-bxflbeco/overlay/include/python3.8/cffi
           cwd: /tmp/pip-install-l9cqhb7a/cffi/
      Complete output (36 lines):
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/cffi
      copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-x86_64-3.8
      creating build/temp.linux-x86_64-3.8/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
      c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
          2 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l9cqhb7a/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l9cqhb7a/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hfmcydse/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-bxflbeco/overlay --compile --install-headers /tmp/pip-build-env-bxflbeco/overlay/include/python3.8/cffi Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-bxflbeco/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cffi>=1.4.1; python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.
```

#### Ubuntu
Prior installed:
```
build-essential zlib1g-dev libssl-dev libncurses-dev libffi-dev libsqlite3-dev libreadline-dev libbz2-dev
```

```
root@46ccc0f64713:/# pip3 install awsebcli
Collecting awsebcli
  Downloading https://files.pythonhosted.org/packages/1f/b2/28049bbf969d57e74bfe2675be80417210d05b6f1b9ac878fc90aef1aaa8/awsebcli-3.17.1.tar.gz (242kB)
    100% |################################| 245kB 2.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q_pccclh/awsebcli/setup.py", line 59, in <module>
        long_description=open('README.rst').read() + open('CHANGES.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11727: ordinal not in range(128)
```

### Expected result

Correctly install awsebcli

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

Tested it on alpine:latest as well as ubuntu:latest.
It has been made sure, that gcc is available.

**Comment by rahulrajaram** [comment]
@steerben , from:

```
fatal error: Python.h: No such file or directory
```
 it's evident that you don't have the necessary Python headers. This is neither a GCC nor a EBCLI issue.

Running

```
sudo apk add python3-dev
```

should fix the problem.

**Comment by rahulrajaram** [comment]
Closing this issue as there is nothing more to do right now.
