### ISSUE TITLE
Creating environment from saved config fails with `'PlatformBranch' object has no attribute 'has_healthd_support'`

### ISSUE THREAD

**Issue by kandalf** [aws/aws-elastic-beanstalk-cli#154]
### Description

When trying to create an environment from a saved config it crashes after selecting the platform branch with the following error:
```
ERROR: AttributeError - 'PlatformBranch' object has no attribute 'has_healthd_support'
```
This happens with `awsebcli 3.20.3`  installed both from Homebrew and from pip and using both Python 3.9 and 3.10.

### Steps to reproduce

- Install the `awsebcli` with `pip` or Homebrew
- Choose an environment saved configuration name
- Attempt to create a new environment from this configuration template:
```
eb create test-env --cfg saved-config-name --version app-version-of-choice
```

### Observed result

```
(env) [kandalf@funkymonkey ########]$ eb create test-env --cfg web-api-production-upgrade --version app-2182-220705_XXXXXX --debug
2022-07-06 01:33:42,878 (DEBUG) cement.core.foundation : laying cement for the 'eb' application
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'pre_setup'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'post_setup'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'pre_run'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'post_run'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'pre_argument_parsing'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'post_argument_parsing'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'pre_close'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'post_close'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'signal'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'pre_render'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : defining hook 'post_render'
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : registering hook 'add_handler_override_options' from cement.core.foundation into hooks['post_setup']
2022-07-06 01:33:42,878 (DEBUG) cement.core.hook : registering hook 'handler_override' from cement.core.foundation into hooks['post_argument_parsing']
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'extension' (IExtension)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'log' (ILog)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'config' (IConfig)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'mail' (IMail)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'plugin' (IPlugin)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'output' (IOutput)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'argument' (IArgument)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'controller' (IController)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : defining handler type 'cache' (ICache)
2022-07-06 01:33:42,879 (DEBUG) cement.core.handler : registering handler '<class 'cement.core.extension.CementExtensionHandler'>' into handlers['extension']['cement']
2022-07-06 01:33:42,892 (DEBUG) cement.ext.ext_plugin : plugin config dir /etc/eb/plugins.d does not exist.
2022-07-06 01:33:42,892 (DEBUG) cement.ext.ext_plugin : plugin config dir /Users/kandalf/.eb/plugins.d does not exist.
2022-07-06 01:33:42,898 (DEBUG) ebcli.core.hooks : -- EBCLI Version: 3.20.3
2022-07-06 01:33:42,898 (DEBUG) ebcli.core.hooks : -- Python Version: 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
2022-07-06 01:33:42,898 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,901 (DEBUG) ebcli.objects.sourcecontrol : Getting current branch name by performing `git rev-parse --abbrev-ref HEAD`
2022-07-06 01:33:42,909 (DEBUG) ebcli.objects.sourcecontrol : refactor/upgrade_production_platform
2022-07-06 01:33:42,910 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,913 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,915 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,917 (DEBUG) ebcli.objects.sourcecontrol : Getting current branch name by performing `git rev-parse --abbrev-ref HEAD`
2022-07-06 01:33:42,925 (DEBUG) ebcli.objects.sourcecontrol : refactor/upgrade_production_platform
2022-07-06 01:33:42,925 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,929 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,932 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,935 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,938 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,940 (DEBUG) ebcli.objects.sourcecontrol : Getting current branch name by performing `git rev-parse --abbrev-ref HEAD`
2022-07-06 01:33:42,949 (DEBUG) ebcli.objects.sourcecontrol : refactor/upgrade_production_platform
2022-07-06 01:33:42,949 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,952 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:42,954 (DEBUG) ebcli.lib.elasticbeanstalk : Inside list_platform_versions api wrapper
2022-07-06 01:33:42,954 (DEBUG) ebcli.lib.aws : Creating new Botocore Session
2022-07-06 01:33:42,954 (DEBUG) ebcli.lib.aws : Botocore version: 1.23.54
2022-07-06 01:33:42,962 (DEBUG) ebcli.lib.aws : Creating new Botocore Client for elasticbeanstalk
2022-07-06 01:33:43,038 (DEBUG) ebcli.lib.aws : Successfully created session for elasticbeanstalk
2022-07-06 01:33:43,039 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_versions) to region: us-east-1 with args:{'Filters': [{'Type': 'PlatformOwner', 'Operator': '=', 'Values': ['self']}]}
2022-07-06 01:33:43,812 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-07-06 01:33:43,812 (DEBUG) ebcli.lib.aws : Response: {'PlatformSummaryList': [], 'ResponseMetadata': {'RequestId': '11d09069-8cb8-428e-aba9-5adc8a6ff28c', 'HTTPStatusCode': 200, 'date': 'Wed, 06 Jul 2022 04:33:43 GMT', 'RetryAttempts': 0}}
2022-07-06 01:33:43,812 (DEBUG) ebcli.lib.elasticbeanstalk : Inside list_platform_branches api wrapper
2022-07-06 01:33:43,812 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_branches) to region: us-east-1 with args:{'Filters': [{'Attribute': 'LifecycleState', 'Operator': '!=', 'Values': ['Retired']}]}
2022-07-06 01:33:44,023 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-07-06 01:33:44,023 (DEBUG) ebcli.lib.aws : Response: {'PlatformBranchSummaryList': [{'PlatformName': '.NET Core on Linux', 'BranchName': '.NET Core running on 64bit Amazon Linux 2', 'BranchOrder': '11000', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': '.NET on Windows Server', 'BranchName': 'IIS 10.0 running on 64bit Windows Server 2019', 'BranchOrder': '10000', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard']}, {'PlatformName': '.NET on Windows Server', 'BranchName': 'IIS 10.0 running on 64bit Windows Server Core 2019', 'BranchOrder': '9900', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard']}, {'PlatformName': '.NET on Windows Server', 'BranchName': 'IIS 10.0 running on 64bit Windows Server 2016', 'BranchOrder': '9800', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard']}, {'PlatformName': '.NET on Windows Server', 'BranchName': 'IIS 10.0 running on 64bit Windows Server Core 2016', 'BranchOrder': '9700', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard']}, {'PlatformName': '.NET on Windows Server', 'BranchName': 'IIS 8.5 running on 64bit Windows Server 2012 R2', 'BranchOrder': '9600', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard']}, {'PlatformName': '.NET on Windows Server', 'BranchName': 'IIS 8.5 running on 64bit Windows Server Core 2012 R2', 'BranchOrder': '9500', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard']}, {'PlatformName': 'Docker', 'BranchName': 'Docker running on 64bit Amazon Linux 2', 'BranchOrder': '11000', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Docker', 'BranchName': 'ECS running on 64bit Amazon Linux 2', 'BranchOrder': '10500', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Docker', 'BranchName': 'Multi-container Docker running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Docker', 'BranchName': 'Docker running on 64bit Amazon Linux', 'BranchOrder': '9000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Go', 'BranchName': 'Go 1 running on 64bit Amazon Linux 2', 'BranchOrder': '11000', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Go', 'BranchName': 'Go 1 running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Java', 'BranchName': 'Corretto 11 running on 64bit Amazon Linux 2', 'BranchOrder': '10000', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Java', 'BranchName': 'Corretto 8 running on 64bit Amazon Linux 2', 'BranchOrder': '9900', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Java', 'BranchName': 'Java 8 running on 64bit Amazon Linux', 'BranchOrder': '8900', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Java', 'BranchName': 'Java 7 running on 64bit Amazon Linux', 'BranchOrder': '8800', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Node.js', 'BranchName': 'Node.js 16 running on 64bit Amazon Linux 2', 'BranchOrder': '11300', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Node.js', 'BranchName': 'Node.js 14 running on 64bit Amazon Linux 2', 'BranchOrder': '11200', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Node.js', 'BranchName': 'Node.js 12 running on 64bit Amazon Linux 2', 'BranchOrder': '11100', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Node.js', 'BranchName': 'Node.js running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Packer', 'BranchName': 'Elastic Beanstalk Packer Builder', 'BranchOrder': '10000', 'LifecycleState': 'Supported', 'SupportedTierList': []}, {'PlatformName': 'Ruby', 'BranchName': 'Passenger with Ruby 2.6 running on 64bit Amazon Linux', 'BranchOrder': '8400', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Passenger with Ruby 2.5 running on 64bit Amazon Linux', 'BranchOrder': '8300', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Passenger with Ruby 2.4 running on 64bit Amazon Linux', 'BranchOrder': '8200', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}], 'NextToken': 'AAAAAAAAAAFt0exVVnUmWkzqJfWwH9i5urFVF/4oecu/bq/HWOL5BkhkDRe/4Oet4hkuD4A8LhEE5kaW9lgUwY6LbSeefSVk9OJ0jzPLQnt3lqcjPa1vq2zFPEjfdehCiQPEt2KIJgGa7sJt8fGg3kU6w6JObRTd9lXzQqkHBzCPJep4YUP+4Q==', 'ResponseMetadata': {'RequestId': '75903b09-5630-4d11-b7b2-ef4d3237bc4a', 'HTTPStatusCode': 200, 'date': 'Wed, 06 Jul 2022 04:33:43 GMT', 'RetryAttempts': 0}}
2022-07-06 01:33:44,023 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, list_platform_branches) to region: us-east-1 with args:{'Filters': [{'Attribute': 'LifecycleState', 'Operator': '!=', 'Values': ['Retired']}], 'NextToken': 'AAAAAAAAAAFt0exVVnUmWkzqJfWwH9i5urFVF/4oecu/bq/HWOL5BkhkDRe/4Oet4hkuD4A8LhEE5kaW9lgUwY6LbSeefSVk9OJ0jzPLQnt3lqcjPa1vq2zFPEjfdehCiQPEt2KIJgGa7sJt8fGg3kU6w6JObRTd9lXzQqkHBzCPJep4YUP+4Q=='}
2022-07-06 01:33:44,299 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-07-06 01:33:44,299 (DEBUG) ebcli.lib.aws : Response: {'PlatformBranchSummaryList': [{'PlatformName': 'GlassFish', 'BranchName': 'Preconfigured Docker - GlassFish 5.0 with Java 8 running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'PHP', 'BranchName': 'PHP 8.0 running on 64bit Amazon Linux 2', 'BranchOrder': '11300', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'PHP', 'BranchName': 'PHP 7.4 running on 64bit Amazon Linux 2', 'BranchOrder': '11200', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'PHP', 'BranchName': 'PHP 7.3 running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'PHP', 'BranchName': 'PHP 7.2 running on 64bit Amazon Linux', 'BranchOrder': '9900', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Python', 'BranchName': 'Python 3.8 running on 64bit Amazon Linux 2', 'BranchOrder': '12000', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Python', 'BranchName': 'Python 3.7 running on 64bit Amazon Linux 2', 'BranchOrder': '11000', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Python', 'BranchName': 'Python 3.6 running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Ruby 3.0 running on 64bit Amazon Linux 2', 'BranchOrder': '11300', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Ruby 2.7 running on 64bit Amazon Linux 2', 'BranchOrder': '11200', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Ruby 2.6 running on 64bit Amazon Linux 2', 'BranchOrder': '11100', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Puma with Ruby 2.6 running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Puma with Ruby 2.5 running on 64bit Amazon Linux', 'BranchOrder': '9900', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Ruby', 'BranchName': 'Puma with Ruby 2.4 running on 64bit Amazon Linux', 'BranchOrder': '9800', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Tomcat', 'BranchName': 'Tomcat 8.5 with Corretto 11 running on 64bit Amazon Linux 2', 'BranchOrder': '11300', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Tomcat', 'BranchName': 'Tomcat 8.5 with Corretto 8 running on 64bit Amazon Linux 2', 'BranchOrder': '11200', 'LifecycleState': 'Supported', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Tomcat', 'BranchName': 'Tomcat 8.5 with Java 8 running on 64bit Amazon Linux', 'BranchOrder': '10000', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}, {'PlatformName': 'Tomcat', 'BranchName': 'Tomcat 7 with Java 7 running on 64bit Amazon Linux', 'BranchOrder': '9800', 'LifecycleState': 'Deprecated', 'SupportedTierList': ['WebServer/Standard', 'Worker/SQS/HTTP']}], 'ResponseMetadata': {'RequestId': '1d35fb6a-009e-46ea-8ea4-4a9625fd6309', 'HTTPStatusCode': 200, 'date': 'Wed, 06 Jul 2022 04:33:43 GMT', 'RetryAttempts': 0}}

It appears you are using Docker. Is this correct?
(Y/n):
Select a platform branch.
1) Docker running on 64bit Amazon Linux 2
2) ECS running on 64bit Amazon Linux 2
3) Multi-container Docker running on 64bit Amazon Linux (Deprecated)
4) Docker running on 64bit Amazon Linux (Deprecated)
(default is 1):

2022-07-06 01:33:45,932 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:45,935 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:45,936 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:45,936 (DEBUG) ebcli.lib.elasticbeanstalk : Inside get_storage_location api wrapper
2022-07-06 01:33:45,936 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, create_storage_location) to region: us-east-1 with args:{}
2022-07-06 01:33:46,187 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-07-06 01:33:46,187 (DEBUG) ebcli.lib.aws : Response: {'S3Bucket': 'elasticbeanstalk-us-east-1-570692421943', 'ResponseMetadata': {'RequestId': 'd7af4982-2b4b-4d50-84fd-9479c7c70ea7', 'HTTPStatusCode': 200, 'date': 'Wed, 06 Jul 2022 04:33:45 GMT', 'RetryAttempts': 0}}
2022-07-06 01:33:46,187 (DEBUG) ebcli.lib.aws : Creating new Botocore Client for s3
2022-07-06 01:33:46,218 (DEBUG) ebcli.lib.aws : Successfully created session for s3
2022-07-06 01:33:46,218 (DEBUG) ebcli.lib.aws : Making api call: (s3, put_object) to region: us-east-1 with args:{'Bucket': 'elasticbeanstalk-us-east-1-570692421943', 'Key': 'resources/templates/############-api/web-api-production-upgrade', 'Body': <_io.BufferedReader name='/Users/kandalf/development/###########/.elasticbeanstalk/saved_configs/web-api-production-upgrade.cfg.yml'>}
2022-07-06 01:33:47,275 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2022-07-06 01:33:47,275 (DEBUG) ebcli.lib.aws : Response: {'ResponseMetadata': {'RequestId': '7DZ1018NXBFRE0WF', 'HostId': '+A5ccX92sNTZ0dibjC9gAHUJTHgisVOrIVC2lOd37j60qUMQeoEE61f/y83sgc5MIxvDNbaxLZc=', 'HTTPStatusCode': 200, 'date': 'Wed, 06 Jul 2022 04:33:48 GMT', 'RetryAttempts': 0}, 'ETag': '"f3a46424eec9ac23cc8442279499e4f7"'}
2022-07-06 01:33:47,275 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:47,278 (DEBUG) ebcli.objects.sourcecontrol : Getting current branch name by performing `git rev-parse --abbrev-ref HEAD`
2022-07-06 01:33:47,288 (DEBUG) ebcli.objects.sourcecontrol : refactor/upgrade_production_platform
2022-07-06 01:33:47,289 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:47,292 (DEBUG) ebcli.core.fileoperations : Project root found at: /Users/kandalf/development/###########
2022-07-06 01:33:47,295 (DEBUG) ebcli.operations.createops : Resolving roles
2022-07-06 01:33:47,303 (INFO) eb : Traceback (most recent call last):
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/ebcli/core/abstractcontroller.py", line 92, in default
    self.do_command()
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/ebcli/controllers/create.py", line 281, in do_command
    createops.make_new_env(env_request,
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/ebcli/operations/createops.py", line 49, in make_new_env
    resolve_roles(env_request, interactive)
  File "/Users/kandalf/development/###########/env/lib/python3.10/site-packages/ebcli/operations/createops.py", line 301, in resolve_roles
    env_request.platform.has_healthd_support and
AttributeError: 'PlatformBranch' object has no attribute 'has_healthd_support'

2022-07-06 01:33:47,304 (INFO) eb : AttributeError - 'PlatformBranch' object has no attribute 'has_healthd_support'
```

### Expected result

Environment created successfully

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Monterrey 12.4
2. EBCLI version: `EB CLI 3.20.3 (Python 3.10.)`
3. Python version: `Python 3.10.5`

**Comment by NihalM99** [comment]
Hi @kandalf  are you still facing the issue ? I was able to deploy an EB-CLI environment with a docker image , save the config and then deploy another environment using the saved config . 
Dockerfile : 
```
FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/
EXPOSE 80
```
index.html file :
```
<!DOCTYPE html>
<html>
<head>
    <title>Test Page</title>
</head>
<body>
    <h1>Hello from Docker!</h1>
</body>
</html>
```
With my file directory like :
```
 /a2test]$ ls
Dockerfile  index.html
```
Created the environment using : `eb create first-docker-env` . Environment launched successfully . 
Saved the config for first-docker-env:
```
/a2test]$ eb config save first-docker-env --cfg first-docker-config

Configuration saved at: /local/home/a2test/.elasticbeanstalk/saved_configs/first-docker-config.cfg.yml
```
Was able to create another environment using the saved config and was successful with no errors :
```
 a2test]$ eb create second-docker-env --cfg first-docker-config
Creating application version archive "app-231024_043943519571".
Uploading a2test/app-231024_043943519571.zip to S3. This may take a while.
Upload Complete.
Environment details for: second-docker-env
  Application name: a2test
  Region: us-west-2
  Deployed Version: app-231024_043943519571
  Environment ID: e-darysx5pni
  Platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on 64bit Amazon Linux 2023/4.1.0
  Tier: WebServer-Standard-1.0
  CNAME: UNKNOWN
  Updated: 2023-10-24 04:39:46.864000+00:00
Printing Status:
2023-10-24 04:39:45    INFO    createEnvironment is starting.
2023-10-24 04:39:47    INFO    Using elasticbeanstalk-us-west-2-564691073335 as Amazon S3 storage bucket for environment data.
2023-10-24 04:40:07    INFO    Created security group named: sg-057f58c9761201402
2023-10-24 04:40:22    INFO    Created security group named: awseb-e-darysx5pni-stack-AWSEBSecurityGroup-1GZ03HXRJ1ALD
2023-10-24 04:40:22    INFO    Created Auto Scaling launch configuration named: awseb-e-darysx5pni-stack-AWSEBAutoScalingLaunchConfiguration-GN40YpYGqwyI
2023-10-24 04:40:22    INFO    Created target group named: arn:aws:elasticloadbalancing:us-west-2:564691073335:targetgroup/awseb-AWSEB-MCXZHSENQTZZ/570a13727f9e8053
2023-10-24 04:40:38    INFO    Created Auto Scaling group named: awseb-e-darysx5pni-stack-AWSEBAutoScalingGroup-0ZJ5EZLjlKDu
2023-10-24 04:40:38    INFO    Waiting for EC2 instances to launch. This may take a few minutes.
2023-10-24 04:40:38    INFO    Created Auto Scaling group policy named: arn:aws:autoscaling:us-west-2:564691073335:scalingPolicy:da972858-a168-4fd1-84e3-6da9fd3c521f:autoScalingGroupName/awseb-e-darysx5pni-stack-AWSEBAutoScalingGroup-0ZJ5EZLjlKDu:policyName/awseb-e-darysx5pni-stack-AWSEBAutoScalingScaleUpPolicy-9bKn72OxsLix
2023-10-24 04:40:38    INFO    Created Auto Scaling group policy named: arn:aws:autoscaling:us-west-2:564691073335:scalingPolicy:9278937c-56de-44eb-b7b0-551e547e7040:autoScalingGroupName/awseb-e-darysx5pni-stack-AWSEBAutoScalingGroup-0ZJ5EZLjlKDu:policyName/awseb-e-darysx5pni-stack-AWSEBAutoScalingScaleDownPolicy-RgoYQ8ftfCna
2023-10-24 04:40:38    INFO    Created CloudWatch alarm named: awseb-e-darysx5pni-stack-AWSEBCloudwatchAlarmHigh-KPzGYhTW7IiZ
2023-10-24 04:40:38    INFO    Created CloudWatch alarm named: awseb-e-darysx5pni-stack-AWSEBCloudwatchAlarmLow-deQasHHgf86d
2023-10-24 04:42:59    INFO    Created load balancer named: arn:aws:elasticloadbalancing:us-west-2:564691073335:loadbalancer/app/awseb--AWSEB-yufHMbSGC6JB/e0cdfd9e7c820c41
2023-10-24 04:42:59    INFO    Created Load Balancer listener named: arn:aws:elasticloadbalancing:us-west-2:564691073335:listener/app/awseb--AWSEB-yufHMbSGC6JB/e0cdfd9e7c820c41/c65fac3c92dfd413
2023-10-24 04:43:22    INFO    Instance deployment completed successfully.
2023-10-24 04:43:35    INFO    Application available at second-docker-env.eba-ug3bptkb.us-west-2.elasticbeanstalk.com.
2023-10-24 04:43:35    INFO    Successfully launched environment: second-docker-env
```
Seems to be working as expected .

**Comment by NihalM99** [comment]
Hi @kandalf , I am using EB-CLI 3.20.10 and python 3.11

**Comment by kandalf** [comment]
> Hi @kandalf , I am using EB-CLI 3.20.10 and python 3.11

Alright, maybe that's the answer. Maybe the `PlatformBranch` object changed in this patch, it was a minor issue anyway.

**Comment by StubbornDeer** [comment]
Hey guys, I hit this error and it prevents me from creating and deploying an app, please help, it's very important and urgent!

**Comment by nishimura-d** [comment]
I ran into this bug with EB CLI 3.21.0.
I got around it by adding the `--platform` option.

**Comment by alexomon018** [comment]
> I ran into this bug with EB CLI 3.21.0. I got around it by adding the `--platform` option.

This helped me!
