### ISSUE TITLE
pip3 install awsebcli --upgrade --user fails for version 3.20.4

### ISSUE THREAD

**Issue by mbonfoster** [aws/aws-elastic-beanstalk-cli#328]
### Description

Getting a subprocess-exited-with-error error when running pip3 install awsebcli --upgrade --user.

### Steps to reproduce

Run pip3 install awsebcli --upgrade --user

python-version: 3.10
Ubuntu 22.04.2

### Observed result

```
Run pip3 install awsebcli --upgrade --user
  pip3 install awsebcli --upgrade --user
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
    Python[2](https://github.com/***)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/***).10.10/x6[4](***)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
Collecting awsebcli
  Downloading awsebcli-3.20.4.tar.gz (260 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.7/260.7 kB [5](https://github.com/***).2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [[6](https://github.com/***) lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-v3hoxhsj/awsebcli_1be[7](https://github.com/***)f47eea39472da[8](https://github.com/***)[9](https://github.com/***)abf[10](https://github.com/***", line [22](https://github.com/***), in <module>
          with open("requirements.txt") as req:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

### Expected result

Work normally, as previous version. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04.2
2. EBCLI version: 3.20.4

**Comment by kirillrdy** [comment]
duplicate of https://github.com/aws/aws-elastic-beanstalk-cli/issues/327

**Comment by mbonfoster** [comment]
Closing. Duplicated while I was writing it.
