### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by BFASKarlR** [aws/aws-elastic-beanstalk-cli#40]
### Description

Just installed eb cli from this repository.  I'm getting the following error from an eb project that previously worked:
ERROR: ServiceError - Configuration validation exception: Invalid option value: 'null' (Namespace: 'aws:ec2:vpc', OptionName: 'Subnets'): Specify the subnets for the VPC for load balancer type application.

### Steps to reproduce

The eb project is pretty complex with several extensions.  But all I do to make it happen is call eb create like the following:
% eb create nkut-org-qa --instance_profile bfas-oldweb-role-acct-ec2-elasticbeanstalk-default

### Observed result
NOTE:  Could not include the entire result, too many characters. 
 % eb create nkut-org-qa --instance_profile bfas-oldweb-role-acct-ec2-elasticbeanstalk-default --debug
2020-07-28 12:17:51,068 (DEBUG) cement.core.foundation : laying cement for the 'eb' application
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'pre_setup'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'post_setup'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'pre_run'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'post_run'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'pre_argument_parsing'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'post_argument_parsing'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'pre_close'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'post_close'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'signal'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'pre_render'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : defining hook 'post_render'
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : registering hook 'add_handler_override_options' from cement.core.foundation into hooks['post_setup']
2020-07-28 12:17:51,068 (DEBUG) cement.core.hook : registering hook 'handler_override' from cement.core.foundation into hooks['post_argument_parsing']
...
2020-07-28 12:18:14,508 (INFO) eb : Creating new environment
2020-07-28 12:18:14,508 (DEBUG) ebcli.lib.elasticbeanstalk : Inside create_environment api wrapper
2020-07-28 12:18:14,508 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, create_environment) to region: us-west-1 with args:{'ApplicationName': 'nkxx-org', 'EnvironmentName': 'nkut-org-qa', 'OptionSettings': [{'Namespace': 'aws:elasticbeanstalk:healthreporting:system', 'OptionName': 'SystemType', 'Value': 'enhanced'}, {'Namespace': 'aws:elasticbeanstalk:command', 'OptionName': 'BatchSize', 'Value': '30'}, {'Namespace': 'aws:elasticbeanstalk:command', 'OptionName': 'BatchSizeType', 'Value': 'Percentage'}, {'Namespace': 'aws:elb:policies', 'OptionName': 'ConnectionDrainingEnabled', 'Value': 'true'}, {'Namespace': 'aws:elb:loadbalancer', 'OptionName': 'CrossZone', 'Value': 'true'}, {'Namespace': 'aws:autoscaling:updatepolicy:rollingupdate', 'OptionName': 'RollingUpdateEnabled', 'Value': 'true'}, {'Namespace': 'aws:autoscaling:updatepolicy:rollingupdate', 'OptionName': 'RollingUpdateType', 'Value': 'Health'}, {'Namespace': 'aws:autoscaling:launchconfiguration', 'OptionName': 'IamInstanceProfile', 'Value': 'bfas-oldweb-role-acct-ec2-elasticbeanstalk-default'}, {'Namespace': 'aws:elasticbeanstalk:environment', 'OptionName': 'ServiceRole', 'Value': 'aws-elasticbeanstalk-service-role'}, {'Namespace': 'aws:autoscaling:launchconfiguration', 'OptionName': 'EC2KeyName', 'Value': 'BFAS-ITS-AWSLinux'}, {'Namespace': 'aws:elasticbeanstalk:environment', 'OptionName': 'LoadBalancerType', 'Value': 'application'}], 'PlatformArn': 'arn:aws:elasticbeanstalk:us-west-1::platform/PHP 7.3 running on 64bit Amazon Linux/2.9.8', 'Description': 'Environment created from the EB CLI using "eb create"', 'VersionLabel': 'app-200728_121752'}
2020-07-28 12:18:16,126 (DEBUG) ebcli.lib.aws : Response: {'Error': {'Type': 'Sender', 'Code': 'ConfigurationValidationException', 'Message': "Configuration validation exception: Invalid option value: 'null' (Namespace: 'aws:ec2:vpc', OptionName: 'ELBSubnets'): Specify the subnets for the VPC for load balancer type application."}, 'ResponseMetadata': {'RequestId': 'e3075ea1-15ca-48db-be28-2d2a90a8c667', 'HTTPStatusCode': 400, 'date': 'Tue, 28 Jul 2020 18:18:16 GMT', 'RetryAttempts': 0}}
2020-07-28 12:18:16,126 (DEBUG) ebcli.lib.aws : API call finished, status = 400
2020-07-28 12:18:16,126 (DEBUG) ebcli.lib.aws : Received a 400 Error
2020-07-28 12:18:16,134 (INFO) eb : Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ebcli/lib/aws.py", line 212, in make_api_call
    response_data = operation(**operation_options)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ConfigurationValidationException) when calling the CreateEnvironment operation: Configuration validation exception: Invalid option value: 'null' (Namespace: 'aws:ec2:vpc', OptionName: 'ELBSubnets'): Specify the subnets for the VPC for load balancer type application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/usr/local/lib/python3.8/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.8/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/usr/local/lib/python3.8/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/usr/local/lib/python3.8/site-packages/ebcli/core/abstractcontroller.py", line 92, in default
    self.do_command()
  File "/usr/local/lib/python3.8/site-packages/ebcli/controllers/create.py", line 263, in do_command
    createops.make_new_env(env_request,
  File "/usr/local/lib/python3.8/site-packages/ebcli/operations/createops.py", line 105, in make_new_env
    result, request_id = create_env(env_request,
  File "/usr/local/lib/python3.8/site-packages/ebcli/operations/createops.py", line 223, in create_env
    return elasticbeanstalk.create_environment(env_request)
  File "/usr/local/lib/python3.8/site-packages/ebcli/lib/elasticbeanstalk.py", line 288, in create_environment
    result = _make_api_call('create_environment', **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ebcli/lib/elasticbeanstalk.py", line 37, in _make_api_call
    return aws.make_api_call('elasticbeanstalk',
  File "/usr/local/lib/python3.8/site-packages/ebcli/lib/aws.py", line 221, in make_api_call
    _handle_response_code(e.response, attempt, aggregated_error_message)
  File "/usr/local/lib/python3.8/site-packages/ebcli/lib/aws.py", line 279, in _handle_response_code
    raise error
ebcli.objects.exceptions.ServiceError: Configuration validation exception: Invalid option value: 'null' (Namespace: 'aws:ec2:vpc', OptionName: 'ELBSubnets'): Specify the subnets for the VPC for load balancer type application.

### Expected result

I expect the eb instance to be created.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 10.15.6
2. EBCLI version:  EB CLI 3.18.2 (Python 3.8.5)

**Comment by BFASKarlR** [comment]
This file contains the entire output.
[eberror.txt](https://github.com/aws/aws-elastic-beanstalk-cli/files/4990389/eberror.txt)

**Comment by Palakpatel67** [comment]
Thanks for reaching out. From your output it looks like there might be VPC configurations in .ebextensions and VPC id is specified but subnets are missing. In order to create environment in VPC, we have to specify VPC id and subnets.
