### ISSUE TITLE
eb health throws if env not yet ready

### ISSUE THREAD

**Issue by glensc** [aws/aws-elastic-beanstalk-cli#519]
### Description

Created new eb environment and tried to ssh to it with `eb ssh`, it said it's not running try `eb health`, but that gave exception.

> Elastic Beanstalk is launching your environment. This will take a few minutes.

### Steps to reproduce

Provide steps to replicate. This should include: exact `ebcli` commands, any relevant configuration files(sanitized), platform version, region, as well as any additional information you think is relevant.

### Observed result

```
Exception in thread Thread-1 (_poll_for_health_data):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/aws-elasticbeanstalk/3.20.10_4/libexec/lib/python3.11/site-packages/ebcli/display/data_poller.py", line 141, in _poll_for_health_data
    raise e
  File "/opt/homebrew/Cellar/aws-elasticbeanstalk/3.20.10_4/libexec/lib/python3.11/site-packages/ebcli/display/data_poller.py", line 115, in _poll_for_health_data
    data = self._get_health_data()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-elasticbeanstalk/3.20.10_4/libexec/lib/python3.11/site-packages/ebcli/display/traditional.py", line 126, in _get_health_data
    'environment': self.assemble_environment_data(ids_of_all_instances, instances_registered_with_elb)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-elasticbeanstalk/3.20.10_4/libexec/lib/python3.11/site-packages/ebcli/display/traditional.py", line 42, in assemble_environment_data
    env = elasticbeanstalk.get_environment(app_name=self.app_name, env_name=self.env_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-elasticbeanstalk/3.20.10_4/libexec/lib/python3.11/site-packages/ebcli/lib/elasticbeanstalk.py", line 618, in get_environment
    raise NotFoundError('Environment "' + env_str + '" not Found.')
ebcli.objects.exceptions.NotFoundError: Environment "metabase-v2-env" not Found.
```

### Expected result

Something nice, like error only without a trace.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. EBCLI version:

**Comment by rahulrajaram** [comment]
@glensc , this sounds like a situation where `eb health` did not receive the correct environment name. Did "metabase-v2-env" actually exist at the time?

**Comment by amjadsy** [comment]
@glensc  I attempted to replicate the issue on a Mac as follows and was not able to:

1. Ran `eb create`
2. Ran `eb ssh` (Gave me a message to try `eb health`)
3. Tried `eb health` and `eb health --refresh` neither one threw a stack trace.

Could you validate my repro steps/give me more information? Thanks
