### ISSUE TITLE
eb create compose environments duplicate appversions 

### ISSUE THREAD

**Issue by afrd-ndilworth** [aws/aws-elastic-beanstalk-cli#84]
### Description
When composing environment for platform 'Docker running on 64bit Amazon Linux 2', `eb create` attempts to create multiple modules with duplicated appversion number. 

### Steps to reproduce

Region: us-east-2
Platform: Docker running on 64bit Amazon Linux 2 3.4.3

```
eb init "deploy-app" --region us-east-2 --platform 'Docker running on 64bit Amazon Linux 2'

eb create --env-group-suffix 20210728-1100 \
  --modules deploy-ui  deploy-api  deploy-service1 deploy-service2  \
  --nohang 
```

### Observed result

```
Finished processing application version app-210728_143539
Finished processing application version app-210728_143538
2021-07-28 14:35:44,681 (DEBUG) ebcli.lib.elasticbeanstalk : Inside get_application_versions api wrapper
2021-07-28 14:35:44,681 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, describe_application_versions) to region: us-east-2 with args:{'ApplicationName': 'deploy-app', 'VersionLabels': ['app-210728_143539', 'app-210728_143540']}
2021-07-28 14:35:44,802 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2021-07-28 14:35:44,802 (DEBUG) ebcli.lib.aws : Response: {'ApplicationVersions': [{'ApplicationName': 'deploy-app', 'Description': 'EB-CLI deploy', 'VersionLabel': 'app-210728_143540', 'SourceBundle': {'S3Bucket': 'elasticbeanstalk-us-east-2-180000281086', 'S3Key': 'deploy-app/app-210728_143540.zip'}, 'DateCreated': datetime.datetime(2021, 7, 28, 14, 35, 40, 482000, tzinfo=tzlocal()), 'DateUpdated': datetime.datetime(2021, 7, 28, 14, 35, 40, 482000, tzinfo=tzlocal()), 'Status': 'PROCESSED'}, {'ApplicationName': 'deploy-app', 'Description': 'EB-CLI deploy', 'VersionLabel': 'app-210728_143539', 'SourceBundle': {'S3Bucket': 'elasticbeanstalk-us-east-2-180000281086', 'S3Key': 'deploy-app/app-210728_143539.zip'}, 'DateCreated': datetime.datetime(2021, 7, 28, 14, 35, 39, 641000, tzinfo=tzlocal()), 'DateUpdated': datetime.datetime(2021, 7, 28, 14, 35, 39, 641000, tzinfo=tzlocal()), 'Status': 'PROCESSED'}], 'ResponseMetadata': {'RequestId': '83aed509-6e22-4c91-a900-e6a7d3121738', 'HTTPStatusCode': 200, 'date': 'Wed, 28 Jul 2021 14:35:43 GMT', 'RetryAttempts': 0}}
Finished processing application version app-210728_143540
Finished processing application version app-210728_143539
--- Creating modules ---
2021-07-28 14:35:44,802 (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, compose_environments) to region: us-east-2 with args:{'ApplicationName': 'deploy-app', 'VersionLabels': ['app-210728_143538', 'app-210728_143539', 'app-210728_143539', 'app-210728_143540'], 'GroupName': '202107281424'}
2021-07-28 14:35:44,899 (DEBUG) ebcli.lib.aws : Response: {'Error': {'Type': 'Sender', 'Code': 'ConfigurationValidationException', 'Message': 'Could not find application versions from [app-210728_143539] version label(s).'}, 'ResponseMetadata': {'RequestId': '0e9a3e8f-4daa-4442-b2cc-0dad9b99758c', 'HTTPStatusCode': 400, 'date': 'Wed, 28 Jul 2021 14:35:44 GMT', 'RetryAttempts': 0}}
2021-07-28 14:35:44,899 (DEBUG) ebcli.lib.aws : API call finished, status = 400
2021-07-28 14:35:44,899 (DEBUG) ebcli.lib.aws : Received a 400 Error
2021-07-28 14:35:44,906 (INFO) eb : Traceback (most recent call last):
  File "/home/appveyor/.local/lib/python3.8/site-packages/ebcli/lib/aws.py", line 212, in make_api_call
    response_data = operation(**operation_options)
  File "/home/appveyor/.local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/appveyor/.local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ConfigurationValidationException) when calling the ComposeEnvironments operation: Could not find application versions from [app-210728_143539] version label(s).
```

### Expected result

Expected appversions to be correctly sequentially numbered 

```
... (DEBUG) ebcli.lib.aws : Making api call: (elasticbeanstalk, compose_environments) to region: us-east-2 with args:{'ApplicationName': 'deploy-app', 'VersionLabels': ['app-210728_143538', 'app-210728_143539', 'app-210728_143540', 'app-210728_143541'], 'GroupName': '202107281424'}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04
2. EBCLI version: EB CLI 3.20.0 (Python 3.7.3)

**Comment by Mickeypeng** [comment]
@afrd-ndilworth Thanks for reaching out. In fact, we don't number the appversions sequentially: we use the timestamp to name them. Currently the timestamp is accurate to the second, therefore if multiple appversions created in one sec, such as your case that environment have multiple modules, then there will be duplicate appversions name so it will cause trouble.
Thanks again for reporting this issue. We are currently working on it.
